### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by brenix** [brenix/holos-demo#2]
### 1. Modeling helm values across many environments

We need to be able to set helm values at multiple layers, for multiple clusters or environments (depending on the terminology you want to use).

To break down the layers, here are an example of each:

#### Chart-level defaults

Setting something such as a common affinity or tolerations that all deployments of the chart will use by default (but can be overwritten as needed)

```yaml
affinity:
  nodeAffinity:
    ...
tolerations:
  - key: foo
    operator: Equal
    value: bar
```

#### Values based on a given region

We may want to set labels etc based on the region which the chart is deployed. An good example would be a prometheus deployment

```yaml
prometheus:
  prometheusSpec:
    externalLabels:
      region: us-east-02
```

#### Values based on a given cluster scope (internal clusters, management clusters, customer clusters)

We need to set values based on a given scope (or type) of the cluster. Each cluster scope will typically have a different set of applications, but for the ones that are shared between multiple cluster scopes would have different values. An example of this could be enabling specific cluster policies or networkpolicies

```yaml
# internal clusters
policies:
  mutateLBTrafficPolicy: false

# management clusters
policies:
  mutateLBTrafficPolicy: true

# customer clusters
policies:
  mutateLBTrafficPolicy: true
```

#### Values based on a given cluster stage (e.g prod, dev, staging)

For the different stages of a cluster, we may want to set various values to size things properly. An example can be replicas for a deployment:

```yaml
# dev clusters
replicas: 1
dopplerConfig: dev

# prod clusters
replicas: 3
dopplerConfig: prod
```

#### Values for a specific cluster

Each cluster has a specific network CIDR and other values that are only specific to that cluster, which need to be fed into charts

```
networkAllocations:
  podCIDRs: ["172.26.0.0/20"]
  serviceCIDRs: ["172.26.64.0/23"]

prometheus:
  prometheusSpec:
    externalLabels:
      cluster: us-east-02-internal
```

### 2. Omitting some rendered resources for a particular environment

In some environments, we have a rare use case to omit resources from the rendered output. The upstream charts do not provide a way to do this, therefore our solution today is to leverage a kustomize patch like so:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources
- ...
patches:
- patch: |-
    $patch: delete
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: secret-that-is-not-needed
      namespace: kube-system
```

With holos, this is easy to do as part of the component, but how do we do this at different levels of our environment (e.g per cluster).

### 3. Excluding or pinning components on a per-environment basis

Some clusters may or may not need a particular component deployed to them. In some cases, we also have to pin a specific version of the chart for the given cluster. This should more likely be a part of the deployment pipeline (e.g kargo), but calling it out here as this is a common theme.
